---

- name: setup the glusterfs instance from a primary node
  hosts: gluster_primary
  tasks:
   vars:
      primarynode: gluster.server1.local
      secondnode: gluster.server2.local
      thirdnode: gluster.server3.local
      gfsname: gfs
      mntdir: /data/glusterfs2
      
  - name: link up the second peer
    shell: gluster peer probe {{ secondnode }}
    args:
      executable: /bin/bash

  - name: link up the third peer
    shell: gluster peer probe {{ thirdnode }}
    args:
      executable: /bin/bash

  - name: create 
    shell: gluster volume create {{ gfsname }} replica 3 {{ primarynode }}:{{ mntdir }}/{{ gfsname }} {{ secondnode }}:{{ mntdir }}/{{ gfsname }} {{ thirdnode }}:{{ mntdir }}/{{ gfsnamee }}
    args:
      executable: /bin/bash

  - name: start the new glusterfs volume {{ glusterfsname }}
    shell: gluster start {{ gfsname }}
    args:
      executable: /bin/bash

...
